apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  ports:
  - port: 7077
    name: spark
  - port: 8080
    name: webui
  selector:
    app: spark
    role: master
